

# Stage 1: Build the Angular application
FROM node:16.13.2 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run  build
# Stage 2: Serve the application with Nginx

FROM nginx:1.14.0-alpine
MAINTAINER Richard Chesterwood "richard@inceptiontraining.co.uk"
# Install bash in the Nginx container
RUN apk add --update bash && rm -rf /var/cache/apk/*
# Remove default Nginx static assets
RUN rm -rf /usr/share/nginx/html/*
# Copy the built assets from the build stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]



